name: 'data_warehouse'

config-version: 2
version: '0.1'

profile: 'default'

model-paths: ["models"]

target-path: "target"  # directory which will store compiled SQL files


models:
  data_warehouse: # Change from `my_new_project` to match the previous value for `name:`
    marts:
      analytics:
        +dataset: analytics
      feature_store:
        +dataset: feature_store
      training_tables:
        +dataset: training_tables
    staging:
      application:
        +dataset: staging
    intermediate:
      +dataset: intermediate

    