name: 'data_warehouse'

config-version: 2
version: '0.1'

profile: 'default'

model-paths: ["models"]

target-path: "target"  # directory which will store compiled SQL files


models:
  data_warehouse:
    marts:
      features:
        +dataset: features
    staging:
      application:
        +dataset: application
      restaurant_data:
        +dataset: restaurant_data

    