version: 2

sources:
  - name: application
    database: foodie-355420
    dataset: mock_app_data
    
    tables:
      - name: users
        identifier: dim_user
        description: "mock generated user data"
      - name: objects
        identifier: dim_restaurant
        description: "mock generated user data"
      - name: interactions
        identifier: fct_user_engagement
        description: "mock generated user data"