version: 2

sources:
  - name: application_prod
    database: foodie-355420
    dataset: application_prod
    
    tables:
      - name: dim_restaurant
        identifier: dim_restaurant
        description: "Restaurant table from application database"